plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "ai.amani.amanisdk"
    compileSdk 35
    ndkVersion "27.1.12297006"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        minSdkVersion 23
    }

    buildFeatures {
        dataBinding true
        buildConfig true
    }

    packaging {
        jniLibs {
            pickFirsts += [
                "lib/x86/libc++_shared.so",
                "lib/x86_64/libc++_shared.so",
                "lib/armeabi-v7a/libc++_shared.so",
                "lib/arm64-v8a/libc++_shared.so"
            ]
        }
    }
}

dependencies {
    implementation "com.github.AMANI-AI-ORG:Android.SDK.UI:1.42.0"
    compileOnly 'ai.amani.android:amani-speech-verifier:1.0.0'
}